# SpringBoot's properties available by default
server:
  port: 8282
spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  main:
    web-application-type: servlet
  task:
    execution:
      pool:
        core-size: 8
        queue-capacity: 100
  data:
    mongodb:
      uri: mongodb+srv://ghardaia:ghardaia@localhost/myFirstDatabase?retryWrites=true&w=majority
#      uri: mongodb+srv://ghardaia:ghardaia@localhost/myFirstDatabase?retryWrites=true&w=majority&authSource=admin

# specific to current application
tpd:
  topic-name: advice-topic
  messages-per-request: 10
letters:
  topic-name: letters
  messages-per-request: 10
els:
  topic-name: els
  messages-per-request: 10
file:
#  inputs: 01.json, 02.json
  inputs: 01.json, 02.json, 03.json, 04.json, 05.json
equidistantLetterSequenceGenerator:
  minInterval: 1
  maxInterval: 100
#  maxInterval: 100



