# SpringBoot's properties available by default
server:
  port: 8282
spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
  main:
    web-application-type: servlet
  task:
    execution:
      pool:
        core-size: 8
        queue-capacity: 100
  data:
    mongodb:
      uri: mongodb+srv://ghardaia:ghardaia@localhost/myFirstDatabase?retryWrites=true&w=majority

# specific to current application
tpd:
  topic-name: advice-topic
  messages-per-request: 10



