# SpringBoot's properties available by default
server:
  port: 8282
spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092

# specific to current application
tpd:
  topic-name: advice-topic
  messages-per-request: 10
